# Icarus=iverilog
# TARGET=out
# FLAGS="-g2005"

# all:
# 	@$(Icarus) $(FLAGS) -E half_adder.v half_adder_tb.v
# 	@$(Icarus) $(FLAGS) -s half_adder_tb -o $(TARGET) half_adder_tb.v half_adder.v
# 	@./$(TARGET)
