# VER=verilator
# FLAGS=--binary --assert --timing --trace
# DIR=OUT
# EXE=out
# TOP=half_adder_tb
# OUTPUTS=--sc --cc
# all:
# 	@$(VER) -E half_adder_tb.sv half_adder.sv
# 	@$(VER) $(FLAGS) half_adder_tb.sv half_adder.sv --top $(TOP) --Mdir $(DIR) -o $(EXE)
