# GHDL=ghdl

# FLAGS="--std=08"

# all:
# 	@$(GHDL) -a $(FLAGS) xor_gate.vhd and_gate.vhd half_adder.vhd half_adder_tb.vhd
# 	@$(GHDL) -e $(FLAGS) half_adder_tb
# 	@$(GHDL) -r $(FLAGS) half_adder_tb --wave=wave.ghw --stop-time=1us
